### PR TITLE
[HOPSWORKS-927] TensorBoard could not bind to an unsupported address family

### PR DESCRIPTION
**Pull request by robzor92**

### CODE REVIEW

**Comment by robzor92** [comment]
https://github.com/logicalclocks/hops-testing/pull/301

**Comment by robzor92** [comment]
@SirOibaf @tkakantousis This one can be merged now tests pass.

**Comment by SirOibaf** [comment]
@robzor92 did you also fix hops-util-py?

**Comment by robzor92** [comment]
@SirOibaf yep fixed it

**Pull request merged**
